// <auto-generated />
using EuroSkills2018.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EuroSkills2018.Migrations
{
    [DbContext(typeof(ESDbContext))]
    partial class ESDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("EuroSkills2018.Models.Orszag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orszagok");
                });

            modelBuilder.Entity("EuroSkills2018.Models.Szakma", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Szakmak");
                });

            modelBuilder.Entity("EuroSkills2018.Models.Versenyzo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrszagId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Pont")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SzakmaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrszagId");

                    b.HasIndex("SzakmaId");

                    b.ToTable("Versenyzok");
                });

            modelBuilder.Entity("EuroSkills2018.Models.Versenyzo", b =>
                {
                    b.HasOne("EuroSkills2018.Models.Orszag", "Orszag")
                        .WithMany("Versenyzok")
                        .HasForeignKey("OrszagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EuroSkills2018.Models.Szakma", "Szakma")
                        .WithMany("Versenyzok")
                        .HasForeignKey("SzakmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orszag");

                    b.Navigation("Szakma");
                });

            modelBuilder.Entity("EuroSkills2018.Models.Orszag", b =>
                {
                    b.Navigation("Versenyzok");
                });

            modelBuilder.Entity("EuroSkills2018.Models.Szakma", b =>
                {
                    b.Navigation("Versenyzok");
                });
#pragma warning restore 612, 618
        }
    }
}
